package de.schosin.decs.values;

/**
 * <b>INTERNAL API:</b> This implementation is not intended to be used.
 * 
 * Placeholder for the actual implementation generated by the annotation processor.
 * This type solely exists for the library to compile and should never be included at runtime.
 */
public final class Components {

    /**
     * Returns the metadata for the component type.
     * 
     * @param <T> type of component
     * @param type class of component
     * @return metadata for component
     * @throws IllegalArgumentException for classes not detected as a component during code generation
     */
    public static <T> ComponentMetadata<T> getMetadata(Class<T> type) {
        throw new UnsupportedOperationException(Types.ERROR);
    }

}
