package de.schosin.decs.values;

import java.util.List;
import java.util.Map;

/**
 * <b>INTERNAL API:</b> This implementation is not intended to be used.
 * 
 * Placeholder for the actual implementation generated by the annotation processor.
 * This type solely exists for the library to compile and should never be included at runtime.
 */
public final class Types {

    public static final String ERROR = "This implementation should never be used. Make sure the \"decs-values\" dependency is not on the classpath.";

    /**
     * Returns true if the given class is a valid system, e.g. has a generated implementation.
     * 
     * @param clazz class of system
     * @return metadata for the system or null if not present
     */
    public static SystemMetadata getSystemMetadata(Class<?> clazz) {
        throw new UnsupportedOperationException(ERROR);
    }

    /**
     * Creates all utilities for the world.
     * 
     * @param world instance of InternalWorld
     * @return lookup map
     */
    public static Map<Class<?>, Object> getUtilities(Object world) {
        throw new UnsupportedOperationException(ERROR);
    }

    /**
     * Creates an instance of ArchetypeEntityData.
     *  
     * @param entityBagSize initial size of data bags
     * @param components list of components to initialize
     * @return instance of ArchetypeEntityData
     */
    public static Object createArchetypeEntityData(int entityBagSize, List<Class<?>> components) {
        throw new UnsupportedOperationException(ERROR);
    }

    /**
     * Instantiates the SystemInvocation for the given world.
     *
     * @param clazz class of type extending SystemInvocation
     * @param world instance of InternalWorld
     * @return instance of SystemInvocation
     */
    public static Object getSystemInvocation(Class<?> clazz, Object world) {
        throw new UnsupportedOperationException(ERROR);
    }

}
