package de.schosin.decs.values;

/**
 * <b>INTERNAL API:</b> This implementation is not intended to be used.
 * 
 * Placeholder for the actual implementation generated by the annotation processor.
 * This type solely exists for the library to compile and should never be included at runtime.
 */
public final class Values {

    static {
        if ("".isEmpty()) {
            throw new IllegalStateException("Remove the \"decs-values\" dependency from the classpath.");
        }
    }

}
